package com.example

import com.example.configuration.properties.DataSourceConfigReader
import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.ImportAutoConfiguration
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.ComponentScan
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Import

@SpringBootConfiguration
@EnableConfigurationProperties(DataSourceConfigReader::class)
@ComponentScan("com.example.databasesharding")
class DatabaseShardingConfiguration